#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.6-{build}-{branch}

branches:
  only:
    - master

image: Visual Studio 2015

environment:
  matrix:
    - CONDA: c:\Miniconda37-x64

  global:
    ECMWF: c:\ecmwf
    GIT_CLONE_DIR: $(ECMWF)\git
    MAGICS_PYTHON_SRC: $(GIT_CLONE_DIR)\magics-python
    MAGICS_CXX_SRC: $(GIT_CLONE_DIR)\magics
    MAGICS_TESTS_SRC: $(GIT_CLONE_DIR)\magics-test
    MAGICS_PYTHON_TESTS: $(MAGICS_TESTS_SRC)\test\gallery

# scripts that are called at very beginning, before repo cloning
init:
  # make sure git clones symlinks as symlinks
  - cmd: git config --global core.symlinks true
  # activate conda environment
  - cmd: call %CONDA%\Scripts\activate.bat
  # auto-yes for conda
  - cmd: conda config --set always_yes yes
  # update conda
  - cmd: conda update -n base -c conda-forge conda

clone_folder: $(MAGICS_PYTHON_SRC)

clone_depth: 1

# scripts that run after cloning repository
install:
  # get magics-cxx for the test/python test scripts
  - cmd: git clone --depth 1 https://github.com/ecmwf/magics.git %MAGICS_CXX_SRC%
  - cmd: git clone --depth 1 https://github.com/ecmwf/magics-test.git %MAGICS_TESTS_SRC%
  # install deps
  - cmd: conda install xarray scipy cftime
  - cmd: conda install -c conda-forge magics pytest
  # remove python interface bundled with magics
  - cmd: rm -r %CONDA%\Lib\site-packages\Magics

#---------------------------------#
#       build configuration       #
#---------------------------------#

build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - cmd: cd %MAGICS_PYTHON_SRC%
  - cmd: set PYTHONPATH=%PYTHONPATH%;%MAGICS_PYTHON_SRC%
  - cmd: pytest
