# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# readthedocs config version, config-file/v2.html
version: 2

# Sphinx setup
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

# Python setup
# python:
#   version: 3.7
#   install:
#     - requirements: ci/requirements-dev.txt

# Conda is a build requirement for the docs
conda:
  environment: docs/environment_docs.yml
