#---------------------------------#
#      general configuration      #
#---------------------------------#

sudo: false

branches:
  only:
    - master

language: python

matrix:
  include:
    - os: linux
      dist: xenial
      env:
        MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
        
env:
  global:
    - MAGICS_PYTHON_SRC=${TRAVIS_BUILD_DIR}
    - MAGICS_CXX_SRC=${MAGICS_PYTHON_SRC}/../magics
    - MAGICS_PYTHON_TESTS=${MAGICS_CXX_SRC}/test/python
    - PYTHONPATH=${PYTHONPATH}:${MAGICS_PYTHON_SRC}:.

git:
  depth: 1

before_install:
  # install conda
  - |
    MINICONDA_URL="https://repo.continuum.io/miniconda"
    curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
    bash ${MINICONDA_FILE} -b
  # activate conda
  - source ~/miniconda3/bin/activate
  # auto-yes for conda
  - conda config --set always_yes yes
  # update conda
  #- conda update -n base -c conda-forge conda

install:
  # get magics-cxx for the test/python test scripts
  - git clone --depth 1 https://github.com/ecmwf/magics.git ${MAGICS_CXX_SRC}
  # install deps
  - conda install xarray scipy cftime
  - conda install -c conda-forge magics pytest
  # remove python interface bundled with magics
  - rm -r ${CONDA_PREFIX}/lib/python*/site-packages/Magics

#---------------------------------#
#       build configuration       #
#---------------------------------#

script:
  - cd ${MAGICS_PYTHON_SRC}
  - pytest
