name: Check and publish

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

  release:
    types: [created]

jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        # platform: [windows-latest, ubuntu-latest, macos-latest]
        # python-version: ["3.6", "3.7", "3.8", "3.9"]
        platform: [ubuntu-latest] #, ubuntu-latest, macos-latest]
        python-version: ["3.8"]
        method: ["conda", "ecmwflibs"]

    name: Python ${{ matrix.python-version }} on ${{ matrix.platform }} (${{ matrix.method }})
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get tests
        run: git clone --depth 1 https://github.com/ecmwf/magics-test.git

      - if: matrix.method == 'conda'
        run: |
          conda install -c conda-forge Magics=4.0.0
          conda init bash
          conda activate

      - if: matrix.method == 'ecmwflibs'
        run: pip install ecmwflibs

      - name: Tests
        run: |
          python setup.py develop
          pip install -r tests/requirements.txt
          pytest
        env:
          MAGICS_PYTHON_TESTS: magics-test/test/gallery

  deploy:
    if: ${{ github.event_name == 'release' }}

    name: Upload to Pypi
    needs: checks

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist
          twine upload dist/*

  notify:
    if: ${{ github.event_name == 'release' }}

    name: Send notifications
    needs: deploy

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        repo: ["climetlab"]

    steps:
      - name: Notify ${{ matrix.repo }}
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.NOTIFY_ECMWFLIBS }}
          repo: ${{ matrix.repo }}
          owner: ecmwf
          event_type: magics-python-updated
